name: rlxyz-creator-publish
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        name: Install Packages
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: Format Solidity code.
        with:
          cmd: format
      - uses: borales/actions-yarn@v2.3.0
        name: Remove any existing compilation files
        with:
          cmd: clean
      - uses: borales/actions-yarn@v2.3.0
        name: Compile Solidity code
        with:
          cmd: compile
      - name: Run Prepare Script
        run: |
          chmod +x ./scripts/prepack.sh
          ./scripts/prepack.sh
        shell: bash
      - name: Run Prepare Script
        run: |
          chmod +x ./scripts/prepare-contracts-package.sh
          ./scripts/prepare-contracts-package.sh
        shell: bash
      - uses: borales/actions-yarn@v2.3.0
        name: Publish to NPM
        working-directory: ./contracts
        with:
          cmd: publish
          auth-token: ${{ secrets.NPM_REGISTRY_TOKEN }}
