name: rlxyz-creator-public
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: borales/actions-yarn@v2.3.0
        with:
          auth-token: ${{ secrets.NPM_TOKEN }}
          registry-url: "https://registry.npmjs.org"
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: format
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: publish
