name: rlxyz-creator-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: format
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
